server:
  port: 8088

spring:
  application:
    name: epg-chart
  datasource:
    url: jdbc:mysql://182.245.29.124:3206/Data?useUnicode=true&characterEncoding=UTF-8
    username: paput
    password: paput@2016iptv
    driver-class-name: com.mysql.cj.jdbc.Driver
