server:
  port: 8088

spring:
  application:
    name: epg-chart
  datasource:
    url: jdbc:log4jdbc:mysql://182.245.29.100:3206/Data?useUnicode=true&characterEncoding=UTF-8
    username: paput
    password: 12345
    driver-class-name: net.sf.log4jdbc.DriverSpy